Ds82 us18 grafieken bedrijfsbeheerder
groep-3-there/frontend pull request #139
Opened 2023-12-10 17:41 UTC by EelcoJansma

2023-12-10 19:50 UTC, Rikk010 requested changes

2023-12-10 19:50 UTC, Rikk010 commented on src/layouts/default/Default.vue
> +                                'DEPARTMENT_MANAGE',
moet dit dan ook niet die nieuwe permissie zijn? COMPANY_GRAPH_READ ofzo?

2023-12-11 08:12 UTC, LukevandePol approved these changes
https://www.bing.com/videos/riverview/relatedvideo?q=look+at+this+graph+vine&mid=82A182F8D71945B8546B82A182F8D71945B8546B&FORM=VIRE0&ru=%2fsearch%3fform%3dMOZLBR%26pc%3dMOZI%26q%3dlook%2bat%2bthis%2bgraph%2bvine

2023-12-11 08:20 UTC, TjerkVenema approved these changes

2023-12-11 08:21 UTC, merged