hotfix-Added prettier config
groep-3-there/frontend pull request #35
Opened 2023-11-09 13:11 UTC by LukevandePol

2023-11-09 13:22 UTC, Rikk010 approved these changes

2023-11-09 13:27 UTC, florijnm approved these changes

2023-11-09 14:03 UTC, florijnm requested changes
niet commits na je pull request doen als t goed is gekeurd

2023-11-10 09:20 UTC, Rikk010 reviewed
doe dit bij release pls <3

2023-11-13 11:43 UTC, closed without merging