Patch company code
groep-3-there/frontend pull request #71
Opened 2023-11-24 12:57 UTC by Rikk010

Join company with code
- as sidebar option
- as popup if logged in
- as register item

2023-11-24 13:24 UTC, LukevandePol commented on src/views/ChallengeView.vue
> +    <template v-if="notFound">
wat

2023-11-24 13:25 UTC, LukevandePol commented on src/views/ChallengeView.vue
> +    </template>
wat

2023-11-24 13:29 UTC, LukevandePol commented on src/views/HomeView.vue
deze imports hoeven niet meer toch

2023-11-24 13:30 UTC, LukevandePol requested changes
kijk de dubbele 
imports in homeview

2023-11-24 21:35 UTC, EelcoJansma approved these changes
Ziet er goed uit heren

2023-11-27 08:24 UTC, florijnm approved these changes

2023-11-27 09:26 UTC, LukevandePol approved these changes

2023-11-27 09:27 UTC, merged