Feature ds51 profiel bewerk pagina
groep-3-there/frontend pull request #92
Opened 2023-11-27 21:33 UTC by JelleNHL

Profiel bewerk pagina up to go

2023-11-27 21:35 UTC, Rikk010 approved these changes

2023-11-27 21:50 UTC, Rikk010 commented
lekker
![DSC08358](https://github.com/groep-3-there/frontend/assets/66070072/d0356735-36d1-481b-b4f4-475c3bf9a548)

2023-11-28 08:49 UTC, LukevandePol commented on src/Api.ts
> +    export async function updateUser(ch: User | { id: number }) {
variabele naam ch aanpassen naar iets wat lijkt op user. ch is namelijk oude afkorting van challenge

2023-11-28 08:57 UTC, LukevandePol commented on src/views/EditUserProfileView.vue
> +                                label="Publiek telefoon nummer"
telefoonnummer is één woord

2023-11-28 08:59 UTC, LukevandePol requested changes
- voeg try catch om de api call heen
 - telefoonnummer is 1 woord
 - variabele naam ch aanpassen naar iets wat met user te maken heeft. ch is oude afkorting van challenge

2023-11-29 08:25 UTC, florijnm approved these changes

2023-11-29 08:26 UTC, merged